version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: systemick
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
      - /Users/mike/.composer/vendor/bin/drush:/usr/local/bin/drush
    links:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: drupal
      DB_USERNAME: app
      DB_PASSWORD: letmein
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: app
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
    volumes:
      - ./mysql_data:/var/lib/mysql
  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379
